import { FormEvent, ReactNode, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "bootstrap/dist/css/bootstrap.min.css";
import "./styles.css";
import { Banknote, BarChart3, Bot, ClipboardCheck, FileText, Globe2, Languages, LayoutDashboard, MessageSquareWarning, ShieldCheck, UserCog, Users } from "lucide-react";
import { api, listItems, PlatformUser } from "./api";

type Role = "ADMIN" | "FIELD_OFFICER" | "FINANCE" | "REVIEWER" | "SUPPORT" | "MANAGER" | "AUDITOR";
type Route = "dashboard" | "programs" | "households" | "beneficiaries" | "eligibility" | "enrollment" | "payments" | "pdm" | "complaints" | "budgets" | "audit" | "automation" | "users";
type Entity = { id: string; name?: string; full_name?: string; number?: string; status?: string; currency?: string; program?: string; household?: string; beneficiary?: string; enrollment?: string; channel_config?: string };

const roleRoutes: Record<Route, Role[]> = {
  dashboard: ["ADMIN", "FIELD_OFFICER", "FINANCE", "REVIEWER", "SUPPORT", "MANAGER", "AUDITOR"],
  programs: ["ADMIN", "FINANCE", "MANAGER"], households: ["ADMIN", "FIELD_OFFICER"], beneficiaries: ["ADMIN", "FIELD_OFFICER", "REVIEWER"],
  eligibility: ["ADMIN", "REVIEWER"], enrollment: ["ADMIN", "REVIEWER"], payments: ["ADMIN", "FINANCE", "MANAGER", "AUDITOR"],
  pdm: ["ADMIN", "SUPPORT", "FIELD_OFFICER", "MANAGER"], complaints: ["ADMIN", "SUPPORT", "MANAGER"], budgets: ["ADMIN", "FINANCE", "MANAGER"],
  audit: ["ADMIN", "MANAGER", "AUDITOR"], automation: ["ADMIN", "MANAGER", "REVIEWER"], users: ["ADMIN"],
};
const nav: Array<[Route, string, typeof LayoutDashboard]> = [
  ["dashboard", "Dashboard", LayoutDashboard], ["programs", "Programs", Globe2], ["households", "Households", Users], ["beneficiaries", "Beneficiaries", Users],
  ["eligibility", "Eligibility review", ClipboardCheck], ["enrollment", "Enrollment decisions", ClipboardCheck], ["payments", "Payments", Banknote],
  ["pdm", "PDM", BarChart3], ["complaints", "Complaints", MessageSquareWarning], ["budgets", "Budgets", FileText], ["audit", "Audit", ShieldCheck],
  ["automation", "AI & Automation", Bot], ["users", "User administration", UserCog],
];
const routePaths: Record<Route, string> = { dashboard: "dashboard", programs: "programs", households: "intake/households", beneficiaries: "intake/beneficiaries", eligibility: "eligibility", enrollment: "enrollment", payments: "payments", pdm: "pdm", complaints: "complaints", budgets: "budgets", audit: "audit", automation: "automation", users: "users" };
const routeFromHash = (): Route => {
  const path = location.hash.replace("#/", "");
  return (Object.entries(routePaths).find(([, value]) => value === path)?.[0] as Route) || "dashboard";
};
const translations = {
  en: { title: "Humanitarian Cash Assistance Platform", subtitle: "Secure, accountable assistance delivery", save: "Save", saving: "Saving…", saved: "Saved", failed: "Failed", signOut: "Sign out", language: "العربية" },
  ar: { title: "منصة المساعدات النقدية الإنسانية", subtitle: "تقديم مساعدات آمن وخاضع للمساءلة", save: "حفظ", saving: "جارٍ الحفظ…", saved: "تم الحفظ", failed: "فشل", signOut: "تسجيل الخروج", language: "English" },
};

function Badge({ value }: { value: string }) {
  const tone = /FAILED|HIGH|CRITICAL|REJECTED/.test(value) ? "danger" : /PENDING|SUBMITTED|DRAFT|OPEN|HOLD/.test(value) ? "warning" : /ACTIVE|SUCCESS|VERIFIED|APPROVED|ELIGIBLE|RESOLVED/.test(value) ? "success" : "secondary";
  return <span className={`badge text-bg-${tone}`}>{value}</span>;
}
function Field({ label, name, type = "text", required = false, options, help }: { label: string; name: string; type?: string; required?: boolean; options?: string[]; help?: string }) {
  const id = `field-${name}`;
  return <div className="mb-3"><label className="form-label" htmlFor={id}>{label}{required && " *"}</label>{options ? <select className="form-select" id={id} name={name} required={required}><option value="">Select…</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <input className="form-control" id={id} name={name} type={type} required={required} />}{help && <div className="form-text">{help}</div>}</div>;
}
function Panel({ title, children, action }: { title: string; children: ReactNode; action?: ReactNode }) { return <section className="panel"><div className="panel-title"><h2>{title}</h2>{action}</div>{children}</section>; }
function Table({ headings, rows }: { headings: string[]; rows: ReactNode[][] }) { return <div className="table-responsive"><table className="table align-middle"><thead><tr>{headings.map((heading) => <th scope="col" key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>) : <tr><td colSpan={headings.length}>No records found.</td></tr>}</tbody></table></div>; }
function Message({ status, error }: { status: string; error: string }) { return <div className="status-message" aria-live="polite">{status === "saving" && "Saving. Do not submit again."}{status === "saved" && "Saved successfully."}{status === "failed" && `Could not save: ${error}`}</div>; }

function Login({ onLogin }: { onLogin: (user: PlatformUser) => void }) {
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(""); try { onLogin(await api.login(String(data.get("email")), String(data.get("password")))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Check your email and password."); } finally { setSaving(false); } };
  return <main className="login-page"><form className="login-card" onSubmit={submit}><div className="who-mark" aria-hidden="true">+</div><p className="eyebrow">Humanitarian operations</p><h1>H-CAP sign in</h1><p>Sign in with your staff account to see only the services assigned to your role.</p>{error && <div className="alert alert-danger" role="alert">{error}</div>}<Field label="Work email" name="email" type="email" required /><Field label="Password" name="password" type="password" required /><button className="btn btn-primary w-100" disabled={saving}>{saving ? "Signing in…" : "Sign in"}</button></form></main>;
}

function CreateProgram() {
  const [programs, setPrograms] = useState<Entity[]>([]); const [selected, setSelected] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setPrograms(listItems(await api.list<Entity>("programs"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load programs"); } };
  useEffect(() => { load(); }, []);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setStatus("saving"); setError(""); try { const item = await api.create<Entity>("programs", { name: form.get("name"), country: form.get("country"), country_code: form.get("country_code"), currency: form.get("currency"), reporting_currency: form.get("reporting_currency"), currency_type: "PROGRAM", exchange_rate: "1", timezone: form.get("timezone"), language: form.get("language"), transfer_amount: form.get("transfer_amount"), payment_cycle: form.get("payment_cycle"), status: "DRAFT", workflow_config: {}, country_pack: {} }); setSelected(item.id); event.currentTarget.reset(); setStatus("saved"); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Correct the highlighted fields."); setStatus("failed"); } };
  const channel = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected) { setStatus("failed"); setError("Create or select a program first."); return; } const form = new FormData(event.currentTarget); setStatus("saving"); try { await api.programChannel(selected, { channel_type: form.get("channel_type"), provider_name: form.get("provider_name"), currency: form.get("currency"), is_active: true }); setStatus("saved"); event.currentTarget.reset(); } catch (reason) { setStatus("failed"); setError(reason instanceof Error ? reason.message : "Could not configure channel."); } };
  return <div className="row g-3"><div className="col-xl-7"><Panel title="Create program"><form onSubmit={create}><div className="row"><div className="col-md-6"><Field label="Program name" name="name" required /></div><div className="col-md-6"><Field label="Country" name="country" required /></div><div className="col-md-4"><Field label="Country code" name="country_code" required help="ISO two-letter code, e.g. SD" /></div><div className="col-md-4"><Field label="Program currency" name="currency" required help="ISO code, e.g. SDG" /></div><div className="col-md-4"><Field label="Reporting currency" name="reporting_currency" required /></div><div className="col-md-6"><Field label="Transfer amount" name="transfer_amount" type="number" required /></div><div className="col-md-3"><Field label="Payment cycle" name="payment_cycle" required options={["ONE_TIME", "MONTHLY", "QUARTERLY"]} /></div><div className="col-md-3"><Field label="Language" name="language" required options={["en", "ar"]} /></div><div className="col-md-6"><Field label="Timezone" name="timezone" required /></div></div><button className="btn btn-primary">Create program</button></form><Message status={status} error={error} /></Panel></div><div className="col-xl-5"><Panel title="Configure simulated channel"><select className="form-select mb-3" value={selected} onChange={(event) => setSelected(event.target.value)} aria-label="Select program"> <option value="">Select a program…</option>{programs.map((program) => <option key={program.id} value={program.id}>{program.name}</option>)}</select><form onSubmit={channel}><Field label="Channel type" name="channel_type" required options={["BANK", "MOBILE_MONEY", "CASH", "VOUCHER"]} /><Field label="Simulated provider name" name="provider_name" required /><Field label="Channel currency" name="currency" required /><button className="btn btn-outline-primary">Save simulated channel</button></form></Panel></div><div className="col-12"><Panel title="Programs"><Table headings={["Program", "Currency", "Status"]} rows={programs.map((program) => [program.name ?? "—", program.currency ?? "—", <Badge value={program.status ?? "DRAFT"} />])} /></Panel></div></div>;
}

function Intake({ beneficiary }: { beneficiary: boolean }) {
  const resource = beneficiary ? "beneficiaries" : "households"; const title = beneficiary ? "Register beneficiary" : "Register household"; const [records, setRecords] = useState<Entity[]>([]); const [programs, setPrograms] = useState<Entity[]>([]); const [households, setHouseholds] = useState<Entity[]>([]); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  const load = async () => { try { setRecords(listItems(await api.list<Entity>(resource))); if (beneficiary) setHouseholds(listItems(await api.list<Entity>("households"))); else setPrograms(listItems(await api.list<Entity>("programs"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load this intake page."); } };
  useEffect(() => { load(); }, [beneficiary]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setStatus("saving"); try { const payload = beneficiary ? { household: form.get("household"), number: form.get("number"), full_name: form.get("full_name"), gender: form.get("gender"), phone_last4: form.get("phone_last4"), consent_given: form.get("consent_given") === "on", verification_status: form.get("verification_status"), status: "REGISTERED" } : { program: form.get("program"), household_size: Number(form.get("household_size")), location: form.get("location"), registration_date: form.get("registration_date"), client_generated_id: form.get("client_generated_id") }; await api.create<Entity>(resource, payload); event.currentTarget.reset(); setStatus("saved"); load(); } catch (reason) { setStatus("failed"); setError(reason instanceof Error ? reason.message : "Correct the form fields and try again."); } };
  return <div className="row g-3"><div className="col-xl-5"><Panel title={title}><form onSubmit={save}>{beneficiary ? <><label className="form-label" htmlFor="beneficiary-household">Household *</label><select className="form-select mb-3" id="beneficiary-household" name="household" required><option value="">Select household…</option>{households.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select><Field label="Beneficiary number" name="number" required /><Field label="Full name" name="full_name" required /><Field label="Gender" name="gender" /><Field label="Phone last four digits" name="phone_last4" /><Field label="Verification status" name="verification_status" required options={["PENDING", "VERIFIED", "REJECTED"]} /><div className="form-check mb-3"><input className="form-check-input" id="consent" name="consent_given" type="checkbox" /><label className="form-check-label" htmlFor="consent">Consent recorded</label></div></> : <><label className="form-label" htmlFor="household-program">Program *</label><select className="form-select mb-3" id="household-program" name="program" required><option value="">Select program…</option>{programs.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Field label="Household size" name="household_size" type="number" required /><Field label="Location" name="location" required /><Field label="Registration date" name="registration_date" type="date" required /><Field label="Offline client ID" name="client_generated_id" help="Preserved for controlled offline sync." /></>}<button className="btn btn-primary">Save {beneficiary ? "beneficiary" : "household"}</button></form><Message status={status} error={error} /></Panel></div><div className="col-xl-7"><Panel title={`${beneficiary ? "Beneficiaries" : "Households"} register`}><Table headings={beneficiary ? ["Number", "Name", "Status"] : ["Household ID", "Program", "Location"]} rows={records.map((record) => beneficiary ? [record.number ?? "—", record.full_name ?? "—", <Badge value={record.status ?? "REGISTERED"} />] : [record.id, record.program ?? "—", "Registered household"])} /></Panel></div></div>;
}

function WorkflowPage({ route }: { route: Route }) {
  const config: Record<Route, { title: string; resource: string; fields: Array<[string, string, string?]> }> = {
    eligibility: { title: "Eligibility review", resource: "enrollments", fields: [["Program ID", "program"], ["Beneficiary ID", "beneficiary"], ["Eligibility status", "eligibility_status", "PENDING|ELIGIBLE|INELIGIBLE|ON_HOLD"]] },
    enrollment: { title: "Enrollment decision", resource: "enrollments", fields: [["Enrollment ID", "id"], ["Decision", "status", "APPROVED|REJECTED"]] },
    payments: { title: "Create simulated payment instruction", resource: "payment-instructions", fields: [["Approved enrollment ID", "enrollment"], ["Beneficiary ID", "beneficiary"], ["Channel ID", "channel_config"], ["Amount", "amount"], ["Currency", "currency"]] },
    pdm: { title: "Post-distribution monitoring", resource: "pdm", fields: [["Program ID", "program"], ["Channel", "channel"], ["Location", "location"], ["Received rate", "received_rate"]] },
    complaints: { title: "Register complaint", resource: "complaints", fields: [["Beneficiary ID", "beneficiary"], ["Payment instruction ID (optional)", "instruction"], ["Category", "category"], ["Description", "description"], ["Severity", "severity", "LOW|MEDIUM|HIGH|CRITICAL"]] },
    budgets: { title: "Manage program budget", resource: "budgets", fields: [["Program ID", "program"], ["Currency", "currency"], ["Planned total", "planned_total"], ["Actual total", "actual_total"]] },
    dashboard: { title: "", resource: "", fields: [] }, programs: { title: "", resource: "", fields: [] }, households: { title: "", resource: "", fields: [] }, beneficiaries: { title: "", resource: "", fields: [] }, audit: { title: "", resource: "", fields: [] }, automation: { title: "", resource: "", fields: [] }, users: { title: "", resource: "", fields: [] },
  }; const page = config[route]; const [status, setStatus] = useState(""); const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = Object.fromEntries([...form.entries()].filter(([, value]) => value !== "")); setStatus("saving"); try { if (route === "enrollment") { const id = String(payload.id); delete payload.id; await api.update(page.resource, id, payload); } else { if (route === "complaints") Object.assign(payload, { status: "OPEN" }); if (route === "budgets") Object.assign(payload, { status: "DRAFT", line_items: [] }); await api.create(page.resource, payload); } event.currentTarget.reset(); setStatus("saved"); } catch (reason) { setStatus("failed"); setError(reason instanceof Error ? reason.message : "Correct the fields and try again."); } };
  return <Panel title={page.title}><form className="workflow-form" onSubmit={submit}>{page.fields.map(([label, name, options]) => <Field key={name} label={label} name={name} required={!label.includes("optional")} options={options?.split("|")} type={name.includes("amount") || name.includes("total") || name.includes("rate") ? "number" : "text"} />)}{route === "payments" && <p className="form-text">Django creates the idempotency key. After saving, use the payment event controls on the instruction record.</p>}<button className="btn btn-primary">Save</button></form><Message status={status} error={error} /></Panel>;
}

function Dashboard() { const [summary, setSummary] = useState<Record<string, number> | null>(null); useEffect(() => { api.get<{ dashboards: Record<string, number> }>("/reports/").then((result) => setSummary(result.dashboards)).catch(() => undefined); }, []); const values = summary ?? { beneficiaries: 0, approvals: 0, paid: 0, pending: 0, failed: 0 }; return <><section className="kpi-grid">{Object.entries(values).slice(0, 5).map(([label, value]) => <article className="kpi" key={label}><strong>{String(value)}</strong><span>{label.replaceAll("_", " ")}</span></article>)}</section><Panel title="Operational dashboard"><p>Dashboard figures are deterministic, tenant-scoped, and show only the data permitted to your role. Managers and auditors can inspect reconciliation, complaint, PDM, budget, and audit views.</p></Panel></>; }
function Automation() { return <Panel title="AI and automation foundation"><div className="alert alert-secondary"><strong>Execution disabled.</strong> Data models for signals, reviews, rules, and execution tracking are prepared. AI cannot make eligibility, fraud, or payment decisions, and all AI endpoints remain closed until you implement them.</div><Table headings={["Event", "Human-controlled action", "Status"]} rows={[["PAYMENT_FAILED", "Create exception review", <Badge value="DISABLED" />], ["DUPLICATE_FLAG", "Assign duplicate review", <Badge value="DISABLED" />], ["HIGH_SEVERITY_COMPLAINT", "Escalate to manager", <Badge value="DISABLED" />]]} /></Panel>; }
function UsersPage() { const [users, setUsers] = useState<PlatformUser[]>([]); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const load = () => api.users().then((result) => setUsers(listItems(result))).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load users.")); useEffect(() => { void load(); }, []); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setStatus("saving"); try { await api.createUser({ full_name: String(form.get("full_name")), email: String(form.get("email")), role: String(form.get("role")) as Role, password: String(form.get("password")) }); event.currentTarget.reset(); setStatus("saved"); void load(); } catch (reason) { setStatus("failed"); setError(reason instanceof Error ? reason.message : "Correct the user fields."); } }; return <div className="row g-3"><div className="col-lg-7"><Panel title="Tenant users"><Table headings={["Name", "Email", "Role", "Status"]} rows={users.map((user) => [user.full_name, user.email, user.role, <Badge value={user.is_active ? "ACTIVE" : "INACTIVE"} />])} /></Panel></div><div className="col-lg-5"><Panel title="Add user"><form onSubmit={submit}><Field label="Full name" name="full_name" required /><Field label="Work email" name="email" type="email" required /><Field label="Role" name="role" required options={["FIELD_OFFICER", "FINANCE", "REVIEWER", "SUPPORT", "MANAGER", "AUDITOR", "ADMIN"]} /><Field label="Temporary password" name="password" type="password" required /><button className="btn btn-primary">Create user</button></form><Message status={status} error={error} /></Panel></div></div>; }

function App() {
  const [user, setUser] = useState<PlatformUser | null>(null); const [locale, setLocale] = useState<"en" | "ar">("en"); const [route, setRoute] = useState<Route>(routeFromHash); const t = translations[locale]; const role = user?.role as Role;
  useEffect(() => { const update = () => setRoute(routeFromHash()); addEventListener("hashchange", update); if (localStorage.getItem("hcap_token")) api.me().then(setUser).catch(api.clearToken); return () => removeEventListener("hashchange", update); }, []);
  const go = (target: Route) => { location.hash = `#/${routePaths[target]}`; };
  if (!user) return <Login onLogin={(staff) => { setUser(staff); go("dashboard"); }} />;
  const permittedNav = nav.filter(([item]) => roleRoutes[item].includes(role));
  const content = route === "dashboard" ? <Dashboard /> : route === "programs" ? <CreateProgram /> : route === "households" ? <Intake beneficiary={false} /> : route === "beneficiaries" ? <Intake beneficiary /> : route === "audit" ? <Panel title="Audit history"><p>Searchable audit history is available through the protected API. Every create, approval, payment simulation, resolution, and user action is traceable by tenant.</p></Panel> : route === "automation" ? <Automation /> : route === "users" ? <UsersPage /> : <WorkflowPage route={route} />;
  return <div dir={locale === "ar" ? "rtl" : "ltr"}><a className="skip-link" href="#main">Skip to content</a><aside className="sidebar"><div className="agency-lockup"><div className="who-mark" aria-hidden="true">+</div><div><strong>H-CAP</strong><small>Humanitarian operations</small></div></div><nav aria-label="Primary navigation">{permittedNav.map(([item, label, Icon]) => <button className={`nav-item ${route === item ? "active" : ""}`} key={item} onClick={() => go(item)}><Icon size={17} /> {label}</button>)}</nav><div className="sidebar-footer"><strong>{user.full_name}</strong><small>{user.role}</small></div></aside><main className="workspace" id="main"><header className="topbar"><div><p className="eyebrow">{t.subtitle}</p><h1>{t.title}</h1></div><div className="d-flex gap-2"><button className="btn btn-outline-primary btn-sm" onClick={() => setLocale(locale === "en" ? "ar" : "en")}><Languages size={16} /> {t.language}</button><button className="btn btn-outline-primary btn-sm" onClick={() => { api.clearToken(); setUser(null); }}>{t.signOut}</button></div></header>{content}</main></div>;
}
createRoot(document.getElementById("root")!).render(<App />);
